### ISSUE TITLE
pyodbc/unixODBC related error

### ISSUE THREAD

**Issue by ShaoLinMonk** [deontologician/netezza_sqlalchemy#4]
Hi,
This repository is a great news to me for connecting Netezza with Jupyter notebook. Thanks for your work. 
When running your code, some pyodbc/unixODBC related error comes to me(I am using Mac, in order to use pyodbc, I need to install unixODBC).  It seems that I need to configure the Netezza odbc driver in advance. I am wondering if you have experienced such error and if there is a way to solve it. 

Best Regards,
Monk

**Comment by deontologician** [comment]
Hi there!  I'm afraid I haven't run into this particular error before. I
don't have access to a Netezza machine any more, so I probably won't be
much help in debugging it

**Comment by ShaoLinMonk** [comment]
Cool, thanks for your reply.
